services:
  - type: web
    name: vehicle-damage-assessment
    runtime: docker
    plan: free
    healthCheckPath: /health
    envVars:
      - key: HF_REPO_ID
        value: Pranjaldutta129/vehicle-damage-models
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: HF_TOKEN
        sync: false
      - key: ENABLE_MLFLOW
        value: "false"
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "2"
